language: ruby
rvm:
  - 1.8.6
  - 1.8.7
  - 1.9.1
  - 1.9.2
  - 1.9.3
  - ruby-head
  - jruby
  - ree
matrix:
  allow_failures:
    - rvm: ruby-head
script: "bundle exec rake"
before_install:
 - sudo apt-get update
 - sudo apt-get install idn
